version: '3.1'

services:
    apache:
        build: .
        volumes:
        - .:/var/www/html
        ports:
        - 40:80
        depends_on:
        - mysql
        - phpmyadmin

    mysql:
        image: mysql:latest
        restart: always
        ports:
        - 3309:3306
        environment:
        - MYSQL_ROOT_PASSWORD=root
        volumes:
        - ./docker/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
        - 8050:80
        environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=root